### ISSUE TITLE
Re"activate" agents when more work has to be done

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/autoscaler#157]
Currently we set `NoSchedule` to `true` when an agent isn't needed anymore. In the time it is still processing pipelines, new work could come up, but the agent would not be set to `NoSchedule=false` again. Instead it is removed and a new agent is spawned afterwards.

**Comment by pat-s** [comment]
I came across this just now

![image](https://github.com/woodpecker-ci/autoscaler/assets/8430564/4147e088-f452-43e8-92fa-56c92b2abbd2)

Because I had set `WOODPECKER_MAX_AGENTS`, I also had to wait until the first build was done even though there were plenty of resources available on the active node.

Happy to test!
