### ISSUE TITLE
Specify agent delete grace period

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/autoscaler#73]
Currently unused agents are deleted as soon as the reconciliation loop runs again, instead it could be helpful to have some grace period before removing agents.

**Comment by xoxys** [comment]
This is exactly what `WOODPECKER_AGENT_ALLOWED_STARTUP_TIME` does but as you have renamed this for some reason from `WOODPECKER_MIN_AGE` in https://github.com/woodpecker-ci/autoscaler/pull/5/commits/51e63152b4e8ff10c081350b9a440321bef6b4c3 this var name is now misleading...

**Comment by anbraten** [comment]
> This is exactly what WOODPECKER_AGENT_ALLOWED_STARTUP_TIME does but as you have renamed this for some reason from WOODPECKER_MIN_AGE in https://github.com/woodpecker-ci/autoscaler/commit/51e63152b4e8ff10c081350b9a440321bef6b4c3 this var name is now misleading...

Not really. That way you would make sure an agent is alive for at least x minutes no matter if its active or not. Instead the goal is to have a setting that removes an agent x minutes after its last task was done.

**Comment by OrvilleQ** [comment]
I really hope this feature will be implemented in the near future.

I also had a problem with autoscaler deleting agents so fast that if I push a new commit and woodpecker cancels the last workflow, I have to wait another 4 or 5 minutes to create a new agent. This is really annoying.

**Comment by OrvilleQ** [comment]
> I also had a problem with autoscaler deleting agents so fast that if I push a new commit and woodpecker cancels the last workflow, I have to wait another 4 or 5 minutes to create a new agent. This is really annoying.

And also, in order to achieve as much cost optimization as possible, there should probably have a smarter agent removal rule set.

Take Hetzner for example, if I understand correctly they calculate the cost of VPS and IPs on an hourly basis. If the associated resource is used for less than an hour, it is counted as an hour.

For maximum cost optimization, it might be a good idea to have an idle window and a deletion window. When an Agent is created, it enters an idle window of, say, 58 minutes. The Agent should not be deleted during this time, even if the CI/CD is not running, because the service provider will still charge an hourly rate even if the Agent is recycled. After the idle window ends, enter the deletion window, e.g., 2 minutes. During this time the Agent should be deleted if it meets the conditions and if it is still running then it should go to the next idle window.

**Comment by anbraten** [comment]
So we need somehow the following options, right?:

- inactivity / not connected to server time (includes the time a server needs to initially connect)
- idle time after which we plan to shutdown an agent
- time we wait before an agent scheduled for shutdown is actually shutdown

**Comment by OrvilleQ** [comment]
@anbraten Sorry for the late reply.

I’m not very familiar with Go, so although I’d like to contribute code, I’m not really able to do so. Instead, I’ll jot down the solution design to optimize costs for Hetzner or any VPS provider that charges in units smaller than one month, hoping someone is interested in implementing the corresponding code.

First, I’d like to introduce two essential configuration options: one is the billing cycle (e.g., `WOODPECKER_PROVIDER_BILLING_CYCLE`), and the other is the deletion/release window (e.g., `WOODPECKER_PROVIDER_[DELETION or RELEASE]_WINDOW`). This latter value must be smaller than the billing cycle.

When a runner is dynamically created, the autoscaler records the Unix timestamp at which the server was created (let’s temporarily call it **CREATION_TIME**), and then runs the CI tasks. Once the tasks are finished and it’s time to check whether the resources should be reclaimed, the following steps occur:

1. **Determine how long the VPS has been running.**  
   Subtract the server’s creation timestamp from the current Unix timestamp. This gives the VPS’s runtime in seconds. Let’s call it **RUNNING_TIME**.

2. **Determine the VPS’s position in the current billing cycle.**  
   Take Hetzner as an example: the billing cycle is one hour, i.e., `PROVIDER_BILLING_CYCLE = 1h` (3600s). Repeatedly subtract `PROVIDER_BILLING_CYCLE` from **RUNNING_TIME** until the remainder is less than `PROVIDER_BILLING_CYCLE`. That remainder is the VPS’s position within the current billing cycle, which we’ll call **CURRENT_LOCATION**.

3. **Determine the boundary between the IDLE WINDOW and the RELEASE WINDOW.**  
   Subtract `PROVIDER_RELEASE_WINDOW` from `PROVIDER_BILLING_CYCLE`. The resulting value is the boundary between the IDLE WINDOW and the RELEASE WINDOW, which we’ll call **DIVIDING_POINT**.

4. **Check which side of that boundary the VPS is currently on** by comparing **CURRENT_LOCATION** and **DIVIDING_POINT**:
   - If `CURRENT_LOCATION < DIVIDING_POINT`, the VPS is in the **IDLE WINDOW**. Proceed to step 5.  
   - If `CURRENT_LOCATION >= DIVIDING_POINT`, the VPS is in the **RELEASE WINDOW**. Proceed to step 8.

5. **Since the VPS is in the IDLE WINDOW**, deleting it wouldn’t align with cost-optimization goals, so keep the VPS. Use `DIVIDING_POINT - CURRENT_LOCATION` to calculate how much time remains before entering the next **RELEASE WINDOW** (call this **DISTANCE_TO_NEXT_RELEASE_WINDOW**), and enter a waiting state. Essentially, it’s like running `sleep DISTANCE_TO_NEXT_RELEASE_WINDOW` on a Linux system.  
   - If no new tasks come in during this period, proceed to step 6.  
   - If a new task is assigned, proceed to step 7.

6. **Since no new tasks arrived and the RELEASE WINDOW has been reached**, reclaim (delete) the VPS resources.

7. **Since a new task was assigned**, clear the waiting state and run the task normally. Once it finishes, return to step 1 and recalculate.

8. **Now the system is in the RELEASE WINDOW, and no tasks were assigned…**  

   At this point, I realized we might need to handle a situation where the time it takes to destroy the server is still counted toward the billing cycle. Therefore, I want to introduce an optional configuration option to skip the current cycle window (`WOODPECKER_PROVIDER_SKIP_CYCLE`), which must be smaller than `PROVIDER_RELEASE_WINDOW`.

   If no tasks are assigned, check whether the VPS is within the **SKIP WINDOW**, similar to how we checked for the RELEASE WINDOW before (setp 3&4, calculating dividing points, etc.).  
   - If it’s in the **SKIP WINDOW**, go to step 9.  
   - Otherwise, go to step 10.  
   (If this option is 0, just skip straight to step 10.)

9. **Since the server is in the SKIP WINDOW**, cancel resource reclamation and move on to the next billing cycle. This involves calculating the time to the next **RELEASE WINDOW**, starting a timer, waiting for any new tasks, and so on (eg. step7) .

10. **Since the server is not in the SKIP WINDOW** (or the SKIP WINDOW does not exist at all), reclaim the VPS resources. **THE END**.

If you visualize it as a picture, it roughly looks like this:

![image](https://github.com/user-attachments/assets/1ab5ba3c-6de3-4743-ad1c-5fc05e3e2fdf)

I hope those reading this can understand my idea and be inspired to implement it. If there are any questions, feel free to ask. I’ll respond as soon as possible (at least it won’t take me another eight months this time, trust me bro :)).
